import React, { useState } from "react";
import {
  Box,
  IconButton,
  styled,
  Tooltip,
  Typography,
} from "@mui/material";
import DeleteIcon from "@mui/icons-material/Delete";
import TextSnippetOutlined from "@mui/icons-material/TextSnippetOutlined";
import dayjs from "dayjs";
import { isAutogeneratedRow } from "@mui/x-data-grid-premium";
import DecimalInput from "./DecimalInput";
import { useSelector } from "react-redux";
import NotesModal from "./NotesModal";
import ChangeEntry from "./ChangeEntry";
import { WeekChecker } from "utils/AppUtil";
import { targetPOSIDsForFuturedate } from "constant/Columns";


const HeaderStyledBox = styled(Box)(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  width: "100%",
}));

const DayBox = styled(Box)(({ theme }) => ({
  fontWeight: "700",
  textAlign: "left",
}));
const EmptyBox = styled(Box)(({ theme }) => ({
  width: "100%",
  height: "100%",
}));

const DateBox = styled(Box)(({ theme }) => ({
  fontWeight: "400",
  fontSize: "14px",
  textAlign: "left",
}));

const TotalTypography = styled(Typography)(({ theme }) => ({
  color: "#121212DE",
  fontWeight: "700",
}));

const IconButtonStyle = styled(Box)(({ theme }) => ({
  width: "100%",
  height: "100%",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
}));
const InputStyleBox = styled(Box)(({ theme }) => ({
  width: "100%",
  height: "100%",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  "& .css-m72fcg-MuiFormControl-root-MuiTextField-root": {
    width: "87% !important",
  },
  "& .MuiDataGrid-root": {
    fontWeight: "700",
    fontSize: "16px",
    border: "none",
  },
}));


export const RowsDataColumns = ({
  handleInputChange,
  handleDelete,
  selectedDate,
  dateWiseData,
  status,
  setAlertMsg,
  setAlertOpen,
  setBatchCallType,
  updateTotalRow
}) => {
  const [modalOpen, setModalOpen] = useState(false);
  const [openChangeEntry, setOpenChangeEntry] = useState(false);
  const [activeInputId, setActiveInputId] = useState(null);
  const [rowObject, setRowObject] = useState({});
  const [hasNote, setHasNote] = useState(new Set());
  const totalValue = useSelector((state) => state?.CreateForm?.totals);
  const currentWkStatus = WeekChecker({ weekRange: selectedDate });

  const openNotesPopup = (inputId, row, i) => {
    setModalOpen(true);
    setActiveInputId(inputId);
    if (row[`day${i}Notes`]) {
      const notes = [];
      const noteStrings = row[`day${i}Notes`].split("\n");
      noteStrings.forEach((note) => {
        const noteIntenalArray = note.split(",");
        if (noteIntenalArray[0] && noteIntenalArray[0].trim()) {
          let isRejected = false;
          if (noteIntenalArray[0].startsWith("Rejected Reason")) {
            isRejected = true;
          }
          let noteValue = noteIntenalArray[0];
          if (noteValue.includes("|n")) {
            noteValue = noteValue.replaceAll("|n", "\n");
          }
          const tempNote = {
            id: Math.random(),
            content: noteValue,
            date: noteIntenalArray[1],
            time: noteIntenalArray[2],
            username: noteIntenalArray[3],
            isRejected: isRejected
          };
          notes.push(tempNote);
        }
      });

      setRowObject({
        row: row,
        index: i,
        notes: notes,
      });
    } else {
      setRowObject({
        row: row,
        index: i,
        notes: [],
      });
    }
  };

  const openChangePopup = (inputId, row, i, value) => {
    setActiveInputId(inputId);
    setRowObject({
      row: row,
      index: i,
      value: value,
    });
    setOpenChangeEntry(true);
  };

  const handleSaveNotes = () => {
    setModalOpen(false);
  };
  const handleCloseModal = () => {
    setModalOpen(false);
  };

  const handleCloseEntryModal = () => {
    setOpenChangeEntry(false);
  };

  const getWeekDays = () => {
    let startDate;
    if (Array?.isArray(selectedDate) && selectedDate?.length === 0) {
      startDate = dayjs().startOf("week").add(1, "day");
    } else if (Array.isArray(selectedDate) && selectedDate.length > 0) {
      const [startDateStr] = selectedDate;
      startDate = dayjs(startDateStr, "DD-MMM-YYYY");
    } else if (selectedDate) {
      const [startDateStr] = selectedDate?.split(" - ");
      startDate = dayjs(startDateStr, "DD MMM YYYY");
    } else {
      startDate = dayjs().startOf("week").add(1, "day");
    }

    const weekDays = [];
    for (let i = 0; i < 7; i++) {
      const currentDate = dayjs(startDate).add(i, "day");
      const isToday = currentDate?.isSame(dayjs(), "date");
      const isWeekend = currentDate.day() === 0 || currentDate.day() === 6;
      const isFutureDay = currentDate?.isAfter(dayjs(), "date");

      weekDays.push({
        field: `day${i}`,
        headerName: currentDate?.format("ddd"),
        flex: 1,
        minWidth: 120,
        borderBottom: "5px solid black",
        headerClassName: isToday ? "highlight-column" : "",
        renderHeader: () => (
          <HeaderStyledBox
            justifyContent={"left"}
            sx={{
              borderBottom: isToday ? "4px solid #ED6A15" : "none",
              "& .MuiDataGrid-columnHeaderTitleContainer": {
                borderBottom: "5px solid orange !important",
              },
              "& .css-1k5yziq-MuiDataGrid-root .MuiDataGrid-row--borderBottom .MuiDataGrid-columnHeader":
              {
                borderBottom: "5px solid green !important",
              },
            }}
          >
            <DayBox sx={{ color: isToday ? "#ED6A15" : "#121212DE" }}>
              {currentDate.format("ddd")}
            </DayBox>
            <DateBox style={{ color: isToday ? "#ED6A15" : "#121212DE" }}>
              {currentDate.format("DD MMM")}
            </DateBox>
          </HeaderStyledBox>
        ),
        valueGetter: (value, row) => {
          if (isAutogeneratedRow(row)) {
            return "[this is an autogenerated row]";
          }
          return `${value}`;
        },
        renderCell: (params) => {
          const row = params?.row;
          // check if current WBS is PTO or Holiday
          const isPTO = targetPOSIDsForFuturedate.includes(row[`level`]);
          if (params?.row?.isParent || isAutogeneratedRow(params?.row)) {
            return (
              <EmptyBox
                sx={{
                  backgroundColor: isWeekend
                    ? "#e5f5fc"
                    : isToday
                      ? "#FBE1D0"
                      : "transparent",
                }}
              ></EmptyBox>
            );
          }

          if (params?.row?.totalRow) {
            return (
              <Typography color={params?.value > 24 ? "#f44336 !important" : "textPrimary !important"} fontWeight={700} mt={"1rem"}>
                {params.value}
              </Typography>
            );
          }

          const inputId = `${params.row.id}-day${i}`;
          const isActive = activeInputId === inputId && !modalOpen;
          const inputHasNote = hasNote.has(inputId);
          return (
            <InputStyleBox
              sx={{
                backgroundColor: isWeekend
                  ? "#e5f5fc"
                  : isToday
                    ? "#FBE1D0"
                    : "transparent",
                "& .MuiDataGrid-root": {
                  backgroundColor: isWeekend
                    ? "#e5f5fc"
                    : isToday
                      ? "#FBE1D0"
                      : "transparent",
                },
              }}
            >
              {status === "Approved" ? (
                <Box
                  component="div"
                  sx={{
                    width: "87% !important",
                    verticalAlign: "unset",
                    backgroundColor: "#eeeeee",
                    border: `1px solid #0000004d`,
                    borderRadius: "4px",
                    padding: "0.5rem",
                    height: "1.2rem",
                    "&:hover": {
                      borderColor: "#0000004d",
                    },
                  }}
                  onClick={() => {
                    //   if (!isFirstInput && !isPrevious) {
                    //     setActiveInputId(inputId);
                    //     handleRejection();
                    //   }
                  }}
                >
                  <Typography color="#797b79 !important">
                    {params?.value}
                  </Typography>
                </Box>
              ) : (row[`day${i}STATUS`] === "40" || row[`day${i}STATUS`] === "20" ||
                status === "Pending For Approval" ||
                status === "Rejected") && !row.newRow ? (
                <Box
                  component="div"
                  sx={{
                    width: "87% !important",
                    verticalAlign: "unset",
                    backgroundColor:
                      row[`day${i}STATUS`] === "40" ? "#ef0c0c30" : "#fff",
                    border: `1px solid ${row[`day${i}STATUS`] === "40" ? "#FF0000" : "#0000004d"}`,
                    borderRadius: "4px",
                    padding: "0.5rem",
                    cursor: isFutureDay && currentWkStatus !== "F" && !isPTO ? 'not-allowed' : "pointer",
                    height: "1.2rem",
                    "&:hover": {
                      borderColor:
                        row[`day${i}STATUS`] === "40" ? "#FF0000" : "#0000004d",
                    },
                  }}
                  onClick={() => {
                    if (!(isFutureDay && currentWkStatus !== "F" && !isPTO)) {
                      openChangePopup(inputId, row, i, params?.value);
                    }
                  }}
                >
                  <Typography color={params?.value > 23 ? "#f44336 !important" : "#797b79 !important"}>
                    {params?.value}
                  </Typography>
                </Box>
              ) : (
                <DecimalInput
                  onChange={(value) =>
                    handleInputChange(`day${i}`, value, params?.row?.id)
                  }
                  value={params?.value}
                  readOnly={isFutureDay && currentWkStatus !== "F" && !isPTO} // commented code for allowing edit for Future days
                  inValidValue={params?.value > 23}
                />
              )}
              <Tooltip title="View notes.">
                <IconButton
                  size="small"
                  disabled={!params?.value || params?.value === '0.00'}
                  onClick={() => openNotesPopup(inputId, row, i)}
                >
                  <TextSnippetOutlined
                    sx={{
                      fontWeight: "400",
                      color:
                        row[`day${i}Notes`] !== "" &&
                          row[`day${i}Notes`] !== undefined
                          ? "#ed6a15"
                          : "grey",
                    }}
                  />
                  {/* {row[`day${i}STATUS`] === "40" ? (
                  <TextSnippetIcon sx={{ fontWeight: "400" }} />
                ) : (
                  <TextSnippetOutlined sx={{ fontWeight: "400" }} />
                )} */}
                  {/* sx={{
                    color: row[`day${i}STATUS`] === "40" ? "red" : "grey",
                    fontWeight: "400",
                  }}
                /> */}
                </IconButton>
              </Tooltip>
              <NotesModal
                open={modalOpen}
                onClose={handleCloseModal}
                activeInputId={activeInputId}
                setHasNote={setHasNote}
                rowObject={rowObject}
                setAlertMsg={setAlertMsg}
                setAlertOpen={setAlertOpen}
              />
              <ChangeEntry
                open={openChangeEntry}
                handleClose={handleCloseEntryModal}
                activeInputId={activeInputId}
                rowObject={rowObject}
                setBatchCallType={setBatchCallType}
                updateTotalRow={updateTotalRow}
              />
            </InputStyleBox>
          );
        },
      });
    }
    return weekDays;
  };

  const weekDayColumns = getWeekDays();
  const columns = [
    // {
    //   field: "project",
    //   headerName: "Project",
    //   flex: 1,
    //   minWidth: 180,
    //   renderCell: (params) => (
    //     <Typography mt={"1rem"} fontWeight={700}>
    //       {params.value}
    //     </Typography>
    //   ),
    // },
    // {
    //   field: "title",
    //   headerName: "WBS",
    //   flex: 1,
    //   minWidth: 180,
    //   renderCell: (params) => (
    //     <Stack>
    //       {/* <Tooltip title={params.row.level}></Tooltip> */}
    //       <CustomPopover content={customStepper()}>
    //         <Typography mt={"0.3rem"} fontSize={"0.9rem"}>
    //           {params.row.level}
    //         </Typography>
    //       </CustomPopover>
    //       <Typography fontWeight={700}>{params.row.title}</Typography>
    //     </Stack>
    //   ),
    // },
    ...weekDayColumns,
    {
      field: "weekTotal",
      headerName: "",
      flex: 0.5,
      minWidth: 100,
      renderCell: (params) => {
        if (params.row.isParent || isAutogeneratedRow(params.row)) {
          return <EmptyBox sx={{ backgroundColor: "transparent" }}></EmptyBox>;
        }
        return (
          <IconButtonStyle>
            <TotalTypography>{params.value}</TotalTypography>

            {!params.row.totalRow && (
              <Tooltip title="Delete time entry.">
                <IconButton
                  disabled={status === "Approved"}
                  size="small"
                  color="secondary"
                  onClick={() => handleDelete(params.row.id)}
                >
                  <DeleteIcon />
                </IconButton>
              </Tooltip>
            )}
          </IconButtonStyle>
        );
      },
    },
  ];

  return columns;
};
